#!/usr/bin/env bash

if
  [[ -s "/home/ubuntu/.rvm/gems/ruby-2.1.5@global/environment" ]]
then
  source "/home/ubuntu/.rvm/gems/ruby-2.1.5@global/environment"
  exec rdoc "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ubuntu/.rvm/gems/ruby-2.1.5@global/environment'" >&2
  exit 1
fi
