#!/usr/bin/env bash

if
  [[ -s "/home/ubuntu/.rvm/gems/ruby-2.1.5/environment" ]]
then
  source "/home/ubuntu/.rvm/gems/ruby-2.1.5/environment"
  exec tp-review "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ubuntu/.rvm/gems/ruby-2.1.5/environment'" >&2
  exit 1
fi
